name: 东东农场，东东萌宠，手机狂欢城，费水果

on:
    push:
        branches:
            - master
    schedule:
        - cron: '5 0-18/6 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run jd_pet
              run: npm install
            - run: node jd_818.js
            - run: node jd_fruit.js
            - run: node jd_pet.js
            - run: node jd_fruit.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
