name: 天天提鹅

on:
    push:
        branches:
            - master
    schedule:
        - cron: '*/2 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run jd_daily_egg
              run: npm install
            - run: node jd_daily_egg.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
     
