# File: .github/workflows/赚京豆2.yml
name: 赚京豆2

on:
    push:
        branches:
            - master
    schedule:
        - cron: '10 7 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run '这是一个组合'
              run: npm install
            - run: node jd_car.js
            - run: node jd_syj.js
            - run: node jd_bean_home.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
